# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Publications
    url: '#publications'
    weight: 2
  - name: Poster/Talks
    url: '#talks'
    weight: 3
  - name: Software
    url: '#projects'
    weight: 4
  - name: CV
    url: "#cv"
    weight: 5
  - name: Contact
    url: "#contact"
    weight: 6
