---
title: ""
---

<span style="color:#0A475D;font-size:200%"> Publications </span>

<span style="color:#F4C76D;font-size:85%;"> \† Authors contributed equally </span>
&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:#C54F43;font-size:85%;"> {{< fa file-pdf >}} PDF file &nbsp;&nbsp; {{< fa book-open >}} Citation &nbsp;&nbsp; {{< fa code >}} Code  </span>

<br>

{{< fa solid scroll >}} **Hesselbarth, M.H.K.**, Nowosad, J., de Flamingh, A., Simpkins, C.E., Jung, M., Gerber, G., Bosch, M. (In press). _Computational methods in landscape ecology_. Current Landscape Ecology Reports.
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.** <span style="color:#F4C76D"> \† </span>, Allgeier, J.E. <span style="color:#F4C76D"> \† </span> (2024). _High fish biomass and low nutrient enrichment synergistically enhance stability in a seagrass meta-ecosystem_. Conservation Letters. e13071. [DOI:10.1111/conl.13071](https://doi.org/10.1111/conl.13071).

[{{< fa file-pdf >}}](files/Hesselbarth-2024-ConservLett.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2024-ConservLett.bib) - [{{< fa code >}}](https://doi.org/10.5281/zenodo.10671464)
---

{{< fa solid scroll >}} Munsterman, K., **Hesselbarth, M.H.K.**, Allgeier, J.E. (2024). _Smaller and bolder fish enhance ecosystem-scale primary production around artificial reefs in seagrass beds_. Ecological Applications. e3055. [DOI:10.1002/eap.3055](https://doi.org/10.1002/eap.3055).

[{{< fa file-pdf >}}](files/Munsterman-2024-EcolAppl.pdf) - [{{< fa book-open >}}](Munsterman-2024-EcolAppl.bib) - [{{< fa code >}}](https://doi.org/10.5281/zenodo.12683020)
---

{{< fa solid scroll >}} Nowosad, J., **Hesselbarth, M.H.K.** (2024). _The landscapemetrics and motif packages for measuring landscape patterns and processes_. arxiv, stat.ME. [DOI:10.48550/arxiv.2405.06559](https://doi.org/10.48550/arxiv.2405.06559)

[{{< fa file-pdf >}}](files/Nowosad-2024-arXiv.pdf) - [{{< fa book-open >}}](files/Nowosad-2024-arXiv.bib) - [{{< fa code >}}](https://github.com/Nowosad/r-ecology-book-chapterIII7)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.**, Wiegand, K. (2024). _A simulation study comparing common methods for analyzing species-habitat associations of plants_. Journal of Vegetation Science 35, e13243. [DOI:10.1111/jvs.13243](https://doi.org/10.1111/jvs.13243).

[{{< fa file-pdf >}}](files/Hesselbarth-2024-JVegSci-35-2.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2024-JVegSci-35-2.bib) - [{{< fa code >}}](https://www.doi.org/10.5281/zenodo.10803171)
---

{{< fa solid scroll >}} Shayka, B.F., **Hesselbarth, M.H.K.**, Schill, S.R., Currie, W.S., Allgeier, J.E. (2023). _The natural capital of seagrass beds in the Caribbean: evaluating their ecosystem services and blue carbon trade potential_. Biology Letters 19:20230075. [DOI:10.1098/rsbl.2023.0075](https://doi.org/10.1098/rsbl.2023.0075).

[{{< fa file-pdf >}}](files/Shayka-2023-BiolLett-19-20230075.pdf) - [{{< fa book-open >}}](files/Shayka-2023-BiolLett-19-20230075.bib) - [{{< fa code >}}](https://doi.org/10.5061/dryad.z612jm6h4)
---

{{< fa solid scroll >}} Rubio-Camacho, E.A., **Hesselbarth, M.H.K.**, Flores-Garnica, J.-G., Acosta-Mireles, M. (2023). _Tree mortality in mature temperate forests of central Mexico: A spatial approach_. European Journal of Forest Research 142, 565–577. [DOI:10.1007/s10342-023-01542-3](https://doi.org/10.1007/s10342-023-01542-3).

[{{< fa file-pdf >}}](files/Rubio-Camacho-2023-EurJForestRes-142-3.pdf) - [{{< fa book-open >}}](files/Rubio-Camacho-2023-EurJForestRes-142-3.bib)
---

{{< fa solid scroll >}} Simpkins, C.E., Hanss, S., Spangenberg, M.C., Salecker, J., **Hesselbarth, M.H.K.**, Wiegand, K. (2022). _spectre: An R package to estimate spatially-explicit community composition using sparse data_. Ecography 2022 (12), e06272. [DOI:10.1111/ecog.06272](https://doi.org/10.1111/ecog.06272).

[{{< fa file-pdf >}}](files/Simpkins-2022-Ecography-2022-12.pdf) - [{{< fa book-open >}}](files/Simpkins-2022-Ecography-2022-12.bib) - [{{< fa code >}}](https://github.com/r-spatialecology/spectre_usecase)
---

{{< fa solid scroll >}} Esquivel, K.E. <span style="color:#F4C76D"> \† </span>, **Hesselbarth, M.H.K.** <span style="color:#F4C76D"> \† </span>, Allgeier, J.E. (2022). _Mechanistic support for increased primary production around artificial reefs_. Ecological Applications 32 (6), e2617. [DOI:10.1002/eap.2617](https://doi.org/10.1002/eap.2617).

[{{< fa file-pdf >}}](files/Esquivel-2022-EcolAppl-32-6.pdf) - [{{< fa book-open >}}](files/Esquivel-2022-EcolAppl-32-6.bib) - [{{< fa code >}}](https://github.com/Allgeier-Lab/Esquivel_etal_2021_EcolAppl)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.** (2021). _shar: An R package to analyze species-habitat associations using point pattern analysis._ Journal of Open Source Software 6 (68), 3811. [DOI:10.21105/joss.03811](https://doi.org/10.21105/joss.03811).

[{{< fa file-pdf >}}](files/Hesselbarth-2021-JOpenSourceSoftw-6-68.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2021-JOpenSourceSoftw-6-68.bib) - [{{< fa code >}}](https://github.com/r-spatialecology/shar)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.**, Nowosad, J., Signer, J., Graham, L.J. (2021). _Open-source tools in R for landscape ecology_. Current Landscape Ecology Reports 6 (3), 97-111. [DOI:10.1007/s40823-021-00067-y](https://doi.org/10.1007/s40823-021-00067-y).

[{{< fa file-pdf >}}](files/Hesselbarth-2021-CurrLandscapeEcolRep-6-3.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2021-CurrLandscapeEcolRep-6-3.bib) - [{{< fa code >}}](https://github.com/r-spatialecology/Hesselbarth_et_al_CLER)
---

{{< fa solid scroll >}} Borthwick, R. <span style="color:#F4C76D"> \† </span>, de Flamingh, A. <span style="color:#F4C76D"> \† </span>, **Hesselbarth, M.H.K.** <span style="color:#F4C76D"> \† </span>, Parandhaman, A. <span style="color:#F4C76D"> \† </span>, Wagner, H.H., Abdel Moniem, H.E.M. (2020). _Alternative Quantifications of Landscape Complementation to Model Gene Flow in Banded Longhorn Beetles [Typocerus v. velutinus (Olivier)]_. Frontiers in Genetics 11, 307. [DOI:10.3389/fgene.2020.00307](https://doi.org/10.3389/fgene.2020.00307).

[{{< fa file-pdf >}}](files/Borthwick-2020-FrontGenet-11.pdf) - [{{< fa book-open >}}](files/Borthwick-2020-FrontGenet-11.bib) - [{{< fa code >}}](https://github.com/mhesselbarth/Borthwick_et_al_2019_Front_Genet)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.** (2020). _Analysing and modelling spatial patterns to infer the influence of environmental heterogeneity using point pattern analysis, individual-based simulation modelling and landscape metrics_. Dissertation. University of Goettingen, Goettingen, Germany. [DOI:10.53846/goediss-7959](http://dx.doi.org/10.53846/goediss-7959).

[{{< fa file-pdf >}}](files/Hesselbarth-2020-UniversityofGoettingen.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2020-UniversityofGoettingen.bib)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.**, Sciaini,M., With,K.A., Wiegand,K., Nowosad,J. (2019). _landscapemetrics: An open-source R tool to calculate landscape metrics_. Ecography 42 (10), 1648-1657. [DOI:10.1111/ecog.04617](https://doi.org/10.1111/ecog.04617).

[{{< fa file-pdf >}}](files/Hesselbarth-2019-Ecography-42-10.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2019-Ecography-42-10.bib) - [{{< fa code >}}](https://github.com/mhesselbarth/Hesselbarth_et_al_2019_Ecography)
---

{{< fa solid scroll >}} **Hesselbarth, M.H.K.**, Wiegand, K., Dreber, N., Kellner, K., Esser, D.,Tsvuura, Z. (2018). _Density-dependent spatial patterning of woody plants differs between a semi-arid and a mesic savanna in South Africa_. Journal of Arid Environments 157, 103-112. [DOI:10.1016/j.jaridenv.2018.06.002](https://doi.org/10.1016/j.jaridenv.2018.06.002).

[{{< fa file-pdf >}}](files/Hesselbarth-2018-JAridEnviron-157.pdf) - [{{< fa book-open >}}](files/Hesselbarth-2018-JAridEnviron-157.bib) - [{{< fa code >}}](https://github.com/mhesselbarth/Hesselbarth_et_al_2018_JAE)
---
