---
title: "Poster & Talks"
---

<span style="color:grey;font-size:85%;"> {{< fa globe >}} Homepage &nbsp;&nbsp; {{< fa person-chalkboard >}} Slides &nbsp;&nbsp; {{< fa brands youtube >}} Video &nbsp;&nbsp; {{< fa file-pdf >}} PDF file </span>

{{< fa comment >}} **Hesselbarth, M.H.K.**, and others, 2022. \textit{Advanced R Workshop}. Ecology and Evolutionary Biology Department, University of Michigan. Ann Arbor (USA). Workshop. [{{< fa globe >}}](https://mhesselbarth.github.io/advanced-r-workshop/)

<!-- <br> -->

{{< fa comment >}} **Hesselbarth, M.H.K.**, 2022. _Introduction to R workshop._ Ecology and Evolutionary Biology Department, University of Michigan. Ann Arbor (USA). [{{< fa person-chalkboard >}}](https://mhesselbarth.github.io/introduction-r-workshop/)

<!-- <br> -->

{{< fa comment >}} **Hesselbarth, M.H.K.**, 2021. _Spatial patterns in ecology and what we (hopefully) can learn from them._ Ecology and Evolutionary Biology Department Seminar, University of Michigan. Ann Arbor (USA). [{{< fa person-chalkboard >}}](files/Hesselbarth-2021-EEB.pdf)

<!-- <br> -->

{{< fa comment >}} Nowosad, J., **Hesselbarth, M.H.K.**, 2020. _Introduction to landscape ecology with R._ Annual Meeting International Association of Landscape Ecology North America. Toronto (Canada). [{{< fa person-chalkboard >}}](https://r-spatialecology.github.io/ialena-2020/) [{{< fa brands youtube >}}](https://www.youtube.com/watch?v=jtAxJ-S89qI)

<!-- <br> -->

{{< fa file-image >}}  **Hesselbarth, M.H.K.**, Sciaini, M., Nowosad, J., Hanss, S., 2019 _landscapemetrics. Introducing a new R tool to characterise landscapes._ 10th World Congress International Association of Landscape Ecology. Milano (Italy). [{{< fa file-pdf >}}](files/Hesselbarth_IALE_2019.pdf)

<!-- <br> -->

{{< fa file-image >}} **Hesselbarth, M.H.K.**, Wiegand, K., 2018. _A simulation study comparing methods to analyze species-habitat associations of forest trees._ 48th Annual Meeting of the Ecological Society of Germany, Austria and Switzerland. Vienna (Austria). [{{< fa file-pdf >}}](files/Hesselbarth_GfO_2018.pdf)

<!-- <br> -->
